---
name: Update Templates
on:
  schedule:
    - cron: "0 0 * * 1-5"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  update-template:
    name: Update Templates
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Copying Upstream Files
        uses: appvia/appvia-cicd-workflows/.github/actions/template-update@main
        with:
          branch-name: cudos-template-update
          pull-request-title: CUDOS Template Update
          template-repository: awslabs/cid-data-collection-framework
          template-files: |
            data-collection/deploy/deploy-data-collection.yaml:modules/destination/assets/cloudformation/cudos
            data-exports/deploy/data-exports-aggregation.yaml:assets/cloudformation/cudos
      - name: Create Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v8
        with:
          base: main
          body: "This PR updates the Data Collection Cloudformation template"
          branch-suffix: timestamp
          labels: "chore"
          reviewers: gambol99
          title: "chore: data collection template"